### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by camilodsilva** [camilodsilva/Blog#1]
Tecnologias
- [x] Instalar Node
- [x] Instalar Yarn
- [x] Adicionar repositório remoto
- [x] Instalar ReactJS
- [ ] Suporte a Markdown?

Layout
- [x]  Definir disposição dos componentes
- [ ] Criar favicon
- [ ] Definir troca de tema 

ReactJS
- [ ] Definir ser será ou não single page
- [ ] Entender como funciona o sistema de requests

Security
- [ ] Revisar alertas de seguranças no pacote loadash

Geral
- [ ] Criar um README para o projeto
